/**
 * Synthetic credential generation.
 *
 * Output is FORMAT-COMPATIBLE ONLY. Generated strings are random garbage that
 * merely look like a provider's keys — they are never checked against, and can
 * never be valid at, any real service. Use for test fixtures, parser QA,
 * secret-scanner rule testing and demos.
 */

import { randomToken } from './charset.js';

/** "Account SID" → "account_sid" */
export function slug(label) {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function resolveLength(token, opts) {
  const override = opts.lengths && opts.lengths[token.label];
  if (token.adjustable && Number.isInteger(override)) {
    return Math.min(256, Math.max(1, override));
  }
  return token.length;
}

function resolvePrefix(token, opts) {
  if (token.prefixOptions && token.prefixOptions.length > 0) {
    const idx = opts.prefixIndex ? opts.prefixIndex[token.label] : 0;
    const i = Number.isInteger(idx) ? idx : 0;
    return token.prefixOptions[Math.min(token.prefixOptions.length - 1, Math.max(0, i))];
  }
  return token.prefix || '';
}

/** Assemble one credential (all its template segments, literals included). */
export function assemble(credential, opts = {}, rng) {
  let out = '';
  for (const token of credential.template) {
    if (typeof token === 'string') {
      out += token;
      continue;
    }
    const length = resolveLength(token, opts);
    out += resolvePrefix(token, opts) + randomToken(token.charsetId, length, rng);
  }
  return out;
}

/**
 * Generate one synthetic credential set for a provider.
 * @returns {{text:string, columns:{label:string, value:string}[], values:Record<string,string>}}
 */
export function generateOne(provider, opts = {}, rng) {
  const columns = provider.credentials.map((credential) => ({
    label: credential.label,
    value: assemble(credential, opts, rng),
  }));
  const values = {};
  for (const col of columns) values[slug(col.label)] = col.value;
  const text = provider.compound
    ? columns.map((c) => `${c.label}: ${c.value}`).join('\n')
    : columns.map((c) => c.value).join('\n');
  return { text, columns, values };
}

export function generateBatch(provider, count, opts = {}, rng) {
  if (!Number.isInteger(count) || count < 1 || count > 10000) {
    throw new RangeError('count must be an integer in 1..10000');
  }
  const rows = [];
  for (let i = 0; i < count; i++) rows.push(generateOne(provider, opts, rng));
  return rows;
}

export const FIXTURE_NOTICE =
  'Synthetic test fixtures generated by Keyshape — NOT real credentials. Format-compatible garbage for testing only.';

function csvEscape(value) {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

export function formatTxt(provider, rows) {
  const lines = [`# ${FIXTURE_NOTICE}`, `# provider: ${provider.id}`];
  for (const row of rows) {
    lines.push(row.text);
    lines.push('');
  }
  return lines.join('\n');
}

export function formatCsv(provider, rows) {
  const header = provider.credentials.map((c) => csvEscape(c.label)).join(',');
  const body = rows.map((row) => row.columns.map((c) => csvEscape(c.value)).join(','));
  return [header, ...body].join('\r\n') + '\r\n';
}

export function formatJson(provider, rows) {
  return JSON.stringify(
    {
      _notice: FIXTURE_NOTICE,
      provider: provider.id,
      generated: rows.length,
      fixtures: rows.map((row) =>
        provider.compound ? row.values : { key: row.text }
      ),
    },
    null,
    2
  );
}

export function formatOutput(provider, rows, format) {
  switch (format) {
    case 'csv':
      return formatCsv(provider, rows);
    case 'json':
      return formatJson(provider, rows);
    case 'txt':
    default:
      return formatTxt(provider, rows);
  }
}
